### ISSUE TITLE
关联表添加多项反向关联接口报错

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#971]
https://github.com/undb-xyz/undb/assets/73324423/76108e73-398c-42c8-a66a-8fada75680d3

API：/record.update?batch=1

payload：
{
    "0": {
        "tableId": "tblsa6eo9rz",
        "id": "recn6pz59bm",
        "values": {
            "fldxweeialo": [
                "recvvefg787",
                "recui9gvevk"
            ]
        }
    }
}

Preview：
[
    {
        "error": {
            "message": "insert into `fldx77vsuus_tblsa6eo9rz_adjacency_list` (`from_id`, `to_id`) values ('recvvefg787', 'recn6pz59bm') - UNIQUE constraint failed: fldx77vsuus_tblsa6eo9rz_adjacency_list.to_id, fldx77vsuus_tblsa6eo9rz_adjacency_list.from_id",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "stack": "UniqueConstraintViolationException: insert into `fldx77vsuus_tblsa6eo9rz_adjacency_list` (`from_id`, `to_id`) values ('recvvefg787', 'recn6pz59bm') - UNIQUE constraint failed: fldx77vsuus_tblsa6eo9rz_adjacency_list.to_id, fldx77vsuus_tblsa6eo9rz_adjacency_list.from_id\n    at BetterSqliteExceptionConverter.convertException (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+better-sqlite@5.7.5_jtmlso6cejn62in7qow5xrgf3u/node_modules/@mikro-orm/better-sqlite/BetterSqliteExceptionConverter.js:20:20)\n    at BetterSqliteDriver.convertException (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.5_436olu4ayqeuqwruhg2agpb2aq/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54)\n    at /Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.5_436olu4ayqeuqwruhg2agpb2aq/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RecordSqliteMutationVisitor.commit (file:///Users/sophie/undb/packages/database/sqlite/dist/repository/base-entity-manager.js:33:7)\n    at async file:///Users/sophie/undb/packages/database/sqlite/dist/repository/record/record-sqlite.repository.js:125:7\n    at async fork.getConnection.transactional (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.5_436olu4ayqeuqwruhg2agpb2aq/node_modules/@mikro-orm/core/EntityManager.js:670:29)\n    at async BetterSqliteConnection.transactional (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+knex@5.7.5_trdvqif3kdi36o5jvoulqdtq2m/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)\n    at async NestRecordSqliteRepository.updateOneById (file:///Users/sophie/undb/packages/database/sqlite/dist/repository/record/record-sqlite.repository.js:118:5)\n    at async descriptor.value (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.5_436olu4ayqeuqwruhg2agpb2aq/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:15:20)\n\nprevious SqliteError: insert into `fldx77vsuus_tblsa6eo9rz_adjacency_list` (`from_id`, `to_id`) values ('recvvefg787', 'recn6pz59bm') - UNIQUE constraint failed: fldx77vsuus_tblsa6eo9rz_adjacency_list.to_id, fldx77vsuus_tblsa6eo9rz_adjacency_list.from_id\n    at Client_BetterSQLite3._query (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)\n    at Object.executeQuery (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)\n    at Client.query (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+knex@5.7.5_trdvqif3kdi36o5jvoulqdtq2m/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:173:71)\n    at /Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/transaction.js:363:24\n    at new Promise (<anonymous>)\n    at trxClient.query (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/transaction.js:358:12)\n    at Runner.query (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/runner.js:123:36)\n    at ensureConnectionCallback (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)\n    at Runner.ensureConnection (/Users/sophie/undb/node_modules/.pnpm/knex@2.4.2_better-sqlite3@8.3.0/node_modules/knex/lib/execution/runner.js:300:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                "path": "record.update"
            }
        }
    }
]

**Comment by WanShufen** [comment]
已验收
